global_costmap:
  global_frame: map
  robot_base_frame: base_footprint

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5

  static_map: true

  always_send_full_costmap: true # new, not sure if it helps
 
  plugins: # it needs both a static and an obstacle layer!?!
#   - {name: static_layer,                 type: "costmap_2d::StaticLayer"}
   - {name: static_layer2,                type: "costmap_2d::StaticLayer"}
   - {name: obstacle_layer,               type: "costmap_2d::ObstacleLayer"} # TODO
  # - {name: inflation,                    type: "costmap_2d::InflationLayer"}
#   - {name: imagination_global_layer,     type: "costmap_2d::StaticLayer"} # TODO
  # - {name: imagination_local_layer,      type: "costmap_2d::StaticLayer"} # TODO